version: '3.8'

services:

  db:
    image: postgres:13
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
        - ./backend:/app
      ports:
        - "8000:8000"
      env_file:
        - backend/.env
      depends_on:
        - db
        
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
          - ./frontend:/app
          - ./frontend/node_modules:/app/node_modules
    command: ["sh", "-c", "npm install && npm run dev"]

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt/live/citestingx.com:/etc/letsencrypt/live/citestingx.com:ro
        - /etc/letsencrypt/archive/citestingx.com:/etc/letsencrypt/archive/citestingx.com:ro

      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - frontend
        - backend


volumes:
  postgres_data: